tasks:
  - init: | 
      ls -alR /workspace/.vscode-remote/extensions/contextmapper.context-mapper-vscode-extension-6.6.1/lsp
      cp -vR context-mapper-dsl-6.6.2-SNAPSHOT/* /workspace/.vscode-remote/extensions/contextmapper.context-mapper-vscode-extension-6.6.1/lsp
      ./gradlew clean build
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - contextmapper.context-mapper-vscode-extension
    - jebbs.plantuml
